name: 'API Protector Diff Action'
description: 'Compares two API specification files (JSON/YAML) and reports differences and compatibility.'
author: 'API-PROTECTOR'

inputs:
  old-spec-file:
    description: 'Path to the old API specification file (YAML or JSON).'
    required: true
    type: string
  new-spec-file:
    description: 'Path to the new API specification file (YAML or JSON).'
    required: true
    type: string
  output-file:
    description: 'Optional path to write the diff output.'
    required: false
    type: string
  exit-on-error:
    description: 'Exit with error code if the OpenAPI changes are not compatible.'
    required: false
    type: boolean
    default: 'false'
  silent:
    description: 'Print no output to console.'
    required: false
    type: boolean
    default: 'false'
  verbose:
    description: 'Enable verbose output.'
    required: false
    type: boolean
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    OLD_SPEC_FILE: ${{ inputs.old-spec-file }}
    NEW_SPEC_FILE: ${{ inputs.new-spec-file }}
    OUTPUT_FILE: ${{ inputs.output-file }}
    EXIT_ON_ERROR: ${{ inputs.exit-on-error }}
    SILENT: ${{ inputs.silent }}
    VERBOSE: ${{ inputs.verbose }}